# .github/workflows/app-deploy.yml
name: Java App Build & Deploy (ECR + Helm)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Application/**'
      - 'helm-chart/**'
      - '.github/workflows/app-deploy.yml'
  workflow_dispatch:

env:
  JAR_NAME: greet-app-0.0.1-SNAPSHOT.jar
  ARTIFACT_NAME: greet-app-artifact
  IMAGE_TAG: "1.0.0"

jobs:
  build_test:
    name: Build Java App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package
        working-directory: Application

  publish_job:
    name: Package and Upload JAR
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests and verify build
        run: mvn --batch-mode verify
        working-directory: Application

      - name: Copy JAR to staging
        run: |
          mkdir -p staging/target
          cp Application/target/${{ env.JAR_NAME }} staging/target/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: staging

  ecr_publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: publish_job
    steps:
      - uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: staging

      - name: Restore JAR to expected target location
        run: |
          mkdir -p Application/target
          cp staging/target/${{ env.JAR_NAME }} Application/target/
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
            -f Application/Dockerfile Application

      - name: Push Docker image to ECR
        run: |
          docker push ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

  helm_deploy:
    name: Deploy to EKS using Helm
    runs-on: ubuntu-latest
    needs: ecr_publish
    environment: prod
    env:
      IMAGE_TAG: "1.0.0"

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set up kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Lint Helm chart
        run: helm lint ./helm-chart

      - name: Deploy with Helm
        run: |
          helm upgrade --install greet ./helm-chart \
            --namespace default \
            --set image.repository=${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }} \
            --set image.tag=${IMAGE_TAG} \
            --set image.pullPolicy=Always
