name: Infrastructure Provisioning (Terraform)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'infrastructure/**'
      - '.github/workflows/infra-provision.yml'

env:
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  terraform:
    name: Provision EKS with Terraform
    runs-on: ubuntu-latest
    environment: prod
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        working-directory: infrastructure

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format and Save Changes
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
